/* 
 * This file is auto-generated.
 * DO NOT MODIFY MANUALLY!
 * 
 * Generated by AstNodeGenerator.
 * Last generated: 2012-09-26 11:07:49.
 */

package org.sweble.wikitext.parser.nodes;

import de.fau.cs.osr.ptk.common.ast.NodeList;

/**
 * <h1>External Link</h1> <h2>Grammar</h2>
 * <ul>
 * <li>
 * <p>
 * '[' Url Space* ']'
 * </p>
 * </li>
 * <li>
 * <p>
 * '[' Url Space+ Title ']'
 * </p>
 * </li>
 * </ul>
 * <h2>The title can contain</h2>
 * <ul>
 * <li>
 * <p>
 * InternalLink
 * </p>
 * </li>
 * <li>
 * <p>
 * PageSwitch
 * </p>
 * </li>
 * <li>
 * <p>
 * ParserEntity
 * </p>
 * </li>
 * <li>
 * <p>
 * Signature
 * </p>
 * </li>
 * <li>
 * <p>
 * Ticks
 * </p>
 * </li>
 * <li>
 * <p>
 * XmlReference
 * </p>
 * </li>
 * </ul>
 * <h2>The title cannot contain</h2>
 * <ul>
 * <li>
 * <p>
 * Newline
 * </p>
 * <ul>
 * <li>
 * <p>
 * Tables
 * </p>
 * </li>
 * <li>
 * <p>
 * Headings
 * </p>
 * </li>
 * <li>
 * <p>
 * Horizontal lines
 * </p>
 * </li>
 * <li>
 * <p>
 * Block level elements
 * </p>
 * </li>
 * </ul>
 * </li>
 * <li>
 * <p>
 * ExternalLink
 * </p>
 * </li>
 * <li>
 * <p>
 * PlainExternalLink
 * </p>
 * </li>
 * <li>
 * <p>
 * XmlElement(*)
 * </p>
 * </li>
 * </ul>
 * <h2>The title can syntactically not contain</h2>
 * <ul>
 * <li>
 * <p>
 * Newlines
 * </p>
 * </li>
 * </ul>
 */
public class ExternalLink
		extends
			WtInnerNode2

{
	private static final long serialVersionUID = 1L;
	
	// =========================================================================
	
	public ExternalLink()
	{
		super(new Url(), new NodeList());
		
	}
	
	public ExternalLink(Url target)
	{
		super(target, new NodeList());
		
	}
	
	public ExternalLink(Url target, NodeList title)
	{
		super(target, title);
		
	}
	
	@Override
	public int getNodeType()
	{
		return org.sweble.wikitext.parser.AstNodeTypes.NT_EXTERNAL_LINK;
	}
	
	// =========================================================================
	// Properties
	
	// =========================================================================
	// Children
	
	public final void setTarget(Url target)
	{
		set(0, target);
	}
	
	public final Url getTarget()
	{
		return (Url) get(0);
	}
	
	public final void setTitle(NodeList title)
	{
		set(1, title);
	}
	
	public final NodeList getTitle()
	{
		return (NodeList) get(1);
	}
	
	private static final String[] CHILD_NAMES = new String[] { "target", "title" };
	
	public final String[] getChildNames()
	{
		return CHILD_NAMES;
	}
	
	// =========================================================================
	
}
