/* 
 * This file is auto-generated.
 * DO NOT MODIFY MANUALLY!
 * 
 * Generated by AstNodeGenerator.
 * Last generated: 2012-09-26 11:07:49.
 */

package org.sweble.wikitext.parser.nodes;

import de.fau.cs.osr.ptk.common.ast.AstNodePropertyIterator;

/**
 * <h1>Internal Link</h1>
 */
public class InternalLink
		extends
			WtInnerNode1
		implements
			Cloneable
{
	private static final long serialVersionUID = 1L;
	
	// =========================================================================
	
	public InternalLink()
	{
		super(new LinkTitle());
		
	}
	
	public InternalLink(
			String prefix,
			String target,
			LinkTitle title,
			String postfix)
	{
		super(title);
		setPrefix(prefix);
		setTarget(target);
		setPostfix(postfix);
		
	}
	
	@Override
	public int getNodeType()
	{
		return org.sweble.wikitext.parser.AstNodeTypes.NT_INTERNAL_LINK;
	}
	
	// =========================================================================
	// Properties
	
	private String target;
	
	public final String getTarget()
	{
		return this.target;
	}
	
	public final String setTarget(String target)
	{
		String old = this.target;
		this.target = target;
		return old;
	}
	
	private String prefix;
	
	public final String getPrefix()
	{
		return this.prefix;
	}
	
	public final String setPrefix(String prefix)
	{
		String old = this.prefix;
		this.prefix = prefix;
		return old;
	}
	
	private String postfix;
	
	public final String getPostfix()
	{
		return this.postfix;
	}
	
	public final String setPostfix(String postfix)
	{
		String old = this.postfix;
		this.postfix = postfix;
		return old;
	}
	
	@Override
	public final int getPropertyCount()
	{
		return 3;
	}
	
	@Override
	public final AstNodePropertyIterator propertyIterator()
	{
		return new AstNodePropertyIterator()
		{
			@Override
			protected int getPropertyCount()
			{
				return 3;
			}
			
			@Override
			protected String getName(int index)
			{
				switch (index)
				{
					case 0:
						return "target";
					case 1:
						return "prefix";
					case 2:
						return "postfix";
						
					default:
						throw new IndexOutOfBoundsException();
				}
			}
			
			@Override
			protected Object getValue(int index)
			{
				switch (index)
				{
					case 0:
						return InternalLink.this.getTarget();
					case 1:
						return InternalLink.this.getPrefix();
					case 2:
						return InternalLink.this.getPostfix();
						
					default:
						throw new IndexOutOfBoundsException();
				}
			}
			
			@Override
			protected Object setValue(int index, Object value)
			{
				switch (index)
				{
					case 0:
						return InternalLink.this.setTarget((String) value);
					case 1:
						return InternalLink.this.setPrefix((String) value);
					case 2:
						return InternalLink.this.setPostfix((String) value);
						
					default:
						throw new IndexOutOfBoundsException();
				}
			}
		};
	}
	
	// =========================================================================
	// Children
	
	public final void setTitle(LinkTitle title)
	{
		set(0, title);
	}
	
	public final LinkTitle getTitle()
	{
		return (LinkTitle) get(0);
	}
	
	private static final String[] CHILD_NAMES = new String[] { "title" };
	
	public final String[] getChildNames()
	{
		return CHILD_NAMES;
	}
	
	// =========================================================================
	
	@Override
	public Object clone()
	{
		try
		{
			return super.clone();
		}
		catch (CloneNotSupportedException e)
		{
			assert false;
			return null;
		}
	}
	
}
