/* 
 * This file is auto-generated.
 * DO NOT MODIFY MANUALLY!
 * 
 * Generated by AstNodeGenerator.
 * Last generated: 2012-09-26 11:07:49.
 */

package org.sweble.wikitext.parser.nodes;


/**
 * <h1>Link Target</h1> <h2>Grammar</h2>
 * <ul>
 * <li>
 * <p>
 * LinkOptionTarget ::= [^\u0000-\u001F\u007F\uFFFD<>{}|[\]]+
 * </p>
 * </li>
 * </ul>
 */
public class LinkTarget
		extends
			WtStringContentNode

{
	private static final long serialVersionUID = 1L;
	
	// =========================================================================
	
	public LinkTarget()
	{
		super();
		
	}
	
	public LinkTarget(String content)
	{
		super(content);
		
	}
	
	@Override
	public int getNodeType()
	{
		return org.sweble.wikitext.parser.AstNodeTypes.NT_LINK_TARGET;
	}
	
	// =========================================================================
	// Properties
	
	// =========================================================================
	// Children
	
	// =========================================================================
	
}
