/* 
 * This file is auto-generated.
 * DO NOT MODIFY MANUALLY!
 * 
 * Generated by AstNodeGenerator.
 * Last generated: 2012-09-26 11:07:49.
 */

package org.sweble.wikitext.parser.nodes;

import java.util.List;

import de.fau.cs.osr.ptk.common.EntityMap;
import de.fau.cs.osr.ptk.common.Warning;
import de.fau.cs.osr.ptk.common.ast.AstNodePropertyIterator;
import de.fau.cs.osr.ptk.common.ast.NodeList;

/**
 * <h1>Grammar for MediaWiki Wikitext</h1> <h2>Grammar</h2>
 */
public class ParsedWikitextPage
		extends
			WtContentNode

{
	private static final long serialVersionUID = 1L;
	
	// =========================================================================
	
	public ParsedWikitextPage()
	{
		super();
		
	}
	
	public ParsedWikitextPage(NodeList content, List<Warning> warnings)
	{
		super(content);
		setWarnings(warnings);
		
	}
	
	public ParsedWikitextPage(
			NodeList content,
			List<Warning> warnings,
			EntityMap entityMap)
	{
		super(content);
		setWarnings(warnings);
		setEntityMap(entityMap);
		
	}
	
	@Override
	public int getNodeType()
	{
		return org.sweble.wikitext.parser.AstNodeTypes.NT_PARSED_WIKITEXT_PAGE;
	}
	
	// =========================================================================
	// Properties
	
	private List<Warning> warnings;
	
	public final List<Warning> getWarnings()
	{
		return this.warnings;
	}
	
	public final List<Warning> setWarnings(List<Warning> warnings)
	{
		List<Warning> old = this.warnings;
		this.warnings = warnings;
		return old;
	}
	
	private EntityMap entityMap;
	
	public final EntityMap getEntityMap()
	{
		return this.entityMap;
	}
	
	public final EntityMap setEntityMap(EntityMap entityMap)
	{
		EntityMap old = this.entityMap;
		this.entityMap = entityMap;
		return old;
	}
	
	@Override
	public final int getPropertyCount()
	{
		return 2;
	}
	
	@Override
	public final AstNodePropertyIterator propertyIterator()
	{
		return new AstNodePropertyIterator()
		{
			@Override
			protected int getPropertyCount()
			{
				return 2;
			}
			
			@Override
			protected String getName(int index)
			{
				switch (index)
				{
					case 0:
						return "warnings";
					case 1:
						return "entityMap";
						
					default:
						throw new IndexOutOfBoundsException();
				}
			}
			
			@Override
			protected Object getValue(int index)
			{
				switch (index)
				{
					case 0:
						return ParsedWikitextPage.this.getWarnings();
					case 1:
						return ParsedWikitextPage.this.getEntityMap();
						
					default:
						throw new IndexOutOfBoundsException();
				}
			}
			
			@Override
			protected Object setValue(int index, Object value)
			{
				switch (index)
				{
					case 0:
						return ParsedWikitextPage.this.setWarnings((List<Warning>) value);
					case 1:
						return ParsedWikitextPage.this.setEntityMap((EntityMap) value);
						
					default:
						throw new IndexOutOfBoundsException();
				}
			}
		};
	}
	
	// =========================================================================
	// Children
	
	// =========================================================================
	
}
