/* 
 * This file is auto-generated.
 * DO NOT MODIFY MANUALLY!
 * 
 * Generated by AstNodeGenerator.
 * Last generated: 2012-09-26 11:07:49.
 */

package org.sweble.wikitext.parser.nodes;

import de.fau.cs.osr.ptk.common.ast.AstNodePropertyIterator;

/**
 * <h1>Signature</h1> <h2>Grammar</h2>
 * <ul>
 * <li>
 * <p>
 * '~~~' '~'*
 * </p>
 * </li>
 * </ul>
 */
public class Signature
		extends
			WtLeafNode

{
	private static final long serialVersionUID = 1L;
	
	// =========================================================================
	
	public Signature()
	{
		super();
		
	}
	
	public Signature(int tildeCount)
	{
		super();
		setTildeCount(tildeCount);
		
	}
	
	@Override
	public int getNodeType()
	{
		return org.sweble.wikitext.parser.AstNodeTypes.NT_SIGNATURE;
	}
	
	// =========================================================================
	// Properties
	
	private int tildeCount;
	
	public final int getTildeCount()
	{
		return this.tildeCount;
	}
	
	public final int setTildeCount(int tildeCount)
	{
		int old = this.tildeCount;
		this.tildeCount = tildeCount;
		return old;
	}
	
	@Override
	public final int getPropertyCount()
	{
		return 1;
	}
	
	@Override
	public final AstNodePropertyIterator propertyIterator()
	{
		return new AstNodePropertyIterator()
		{
			@Override
			protected int getPropertyCount()
			{
				return 1;
			}
			
			@Override
			protected String getName(int index)
			{
				switch (index)
				{
					case 0:
						return "tildeCount";
						
					default:
						throw new IndexOutOfBoundsException();
				}
			}
			
			@Override
			protected Object getValue(int index)
			{
				switch (index)
				{
					case 0:
						return Signature.this.getTildeCount();
						
					default:
						throw new IndexOutOfBoundsException();
				}
			}
			
			@Override
			protected Object setValue(int index, Object value)
			{
				switch (index)
				{
					case 0:
						return Signature.this.setTildeCount((Integer) value);
						
					default:
						throw new IndexOutOfBoundsException();
				}
			}
		};
	}
	
	// =========================================================================
	// Children
	
	// =========================================================================
	
}
