/* 
 * This file is auto-generated.
 * DO NOT MODIFY MANUALLY!
 * 
 * Generated by AstNodeGenerator.
 * Last generated: 2012-09-26 11:07:49.
 */

package org.sweble.wikitext.parser.nodes;

import de.fau.cs.osr.ptk.common.ast.AstNodePropertyIterator;

/**
 * <h1>XML Attribute</h1> <h2>Grammar</h2>
 * <ul>
 * <li>
 * <p>
 * Ws* XmlName Ws* '=' Ws* '\'' AttributeValueSq* '\''
 * </p>
 * </li>
 * <li>
 * <p>
 * Ws* XmlName Ws* '=' Ws* '"' ValueDqStar '"'
 * </p>
 * </li>
 * <li>
 * <p>
 * Ws* XmlName Ws* '=' ValueNqStar
 * </p>
 * </li>
 * <li>
 * <p>
 * Ws* XmlName
 * </p>
 * </li>
 * </ul>
 */
public class XmlAttribute
		extends
			WtInnerNode1

{
	private static final long serialVersionUID = 1L;
	
	// =========================================================================
	
	public XmlAttribute()
	{
		super(new WtList());
		
	}
	
	public XmlAttribute(String name, boolean hasValue)
	{
		super(new WtList());
		setName(name);
		setHasValue(hasValue);
		
	}
	
	public XmlAttribute(String name, WtList value, boolean hasValue)
	{
		super(value);
		setName(name);
		setHasValue(hasValue);
		
	}
	
	@Override
	public int getNodeType()
	{
		return org.sweble.wikitext.parser.AstNodeTypes.NT_XML_ATTRIBUTE;
	}
	
	// =========================================================================
	// Properties
	
	private String name;
	
	public final String getName()
	{
		return this.name;
	}
	
	public final String setName(String name)
	{
		String old = this.name;
		this.name = name;
		return old;
	}
	
	private boolean hasValue;
	
	public final boolean getHasValue()
	{
		return this.hasValue;
	}
	
	public final boolean setHasValue(boolean hasValue)
	{
		boolean old = this.hasValue;
		this.hasValue = hasValue;
		return old;
	}
	
	@Override
	public final int getPropertyCount()
	{
		return 2;
	}
	
	@Override
	public final AstNodePropertyIterator propertyIterator()
	{
		return new AstNodePropertyIterator()
		{
			@Override
			protected int getPropertyCount()
			{
				return 2;
			}
			
			@Override
			protected String getName(int index)
			{
				switch (index)
				{
					case 0:
						return "name";
					case 1:
						return "hasValue";
						
					default:
						throw new IndexOutOfBoundsException();
				}
			}
			
			@Override
			protected Object getValue(int index)
			{
				switch (index)
				{
					case 0:
						return XmlAttribute.this.getName();
					case 1:
						return XmlAttribute.this.getHasValue();
						
					default:
						throw new IndexOutOfBoundsException();
				}
			}
			
			@Override
			protected Object setValue(int index, Object value)
			{
				switch (index)
				{
					case 0:
						return XmlAttribute.this.setName((String) value);
					case 1:
						return XmlAttribute.this.setHasValue((Boolean) value);
						
					default:
						throw new IndexOutOfBoundsException();
				}
			}
		};
	}
	
	// =========================================================================
	// Children
	
	public final void setValue(WtList value)
	{
		set(0, value);
	}
	
	public final WtList getValue()
	{
		return (WtList) get(0);
	}
	
	private static final String[] CHILD_NAMES = new String[] { "value" };
	
	public final String[] getChildNames()
	{
		return CHILD_NAMES;
	}
	
	// =========================================================================
	
}
