/* 
 * This file is auto-generated.
 * DO NOT MODIFY MANUALLY!
 * 
 * Generated by AstNodeGenerator.
 * Last generated: 2012-09-26 11:07:49.
 */

package org.sweble.wikitext.parser.nodes;

import de.fau.cs.osr.ptk.common.ast.AstNodePropertyIterator;

/**
 * <h1>Xml Character Reference</h1> <h2>Grammar</h2>
 * <ul>
 * <li>
 * <p>
 * '&#' Digit+ ';'
 * </p>
 * </li>
 * <li>
 * <p>
 * '&#x' HexDigit+ ';'
 * </p>
 * </li>
 * </ul>
 */
public class XmlCharRef
		extends
			WtLeafNode

{
	private static final long serialVersionUID = 1L;
	
	// =========================================================================
	
	public XmlCharRef()
	{
		super();
		
	}
	
	public XmlCharRef(int codePoint)
	{
		super();
		setCodePoint(codePoint);
		
	}
	
	@Override
	public int getNodeType()
	{
		return org.sweble.wikitext.parser.AstNodeTypes.NT_XML_CHAR_REF;
	}
	
	// =========================================================================
	// Properties
	
	private int codePoint;
	
	public final int getCodePoint()
	{
		return this.codePoint;
	}
	
	public final int setCodePoint(int codePoint)
	{
		int old = this.codePoint;
		this.codePoint = codePoint;
		return old;
	}
	
	@Override
	public final int getPropertyCount()
	{
		return 1;
	}
	
	@Override
	public final AstNodePropertyIterator propertyIterator()
	{
		return new AstNodePropertyIterator()
		{
			@Override
			protected int getPropertyCount()
			{
				return 1;
			}
			
			@Override
			protected String getName(int index)
			{
				switch (index)
				{
					case 0:
						return "codePoint";
						
					default:
						throw new IndexOutOfBoundsException();
				}
			}
			
			@Override
			protected Object getValue(int index)
			{
				switch (index)
				{
					case 0:
						return XmlCharRef.this.getCodePoint();
						
					default:
						throw new IndexOutOfBoundsException();
				}
			}
			
			@Override
			protected Object setValue(int index, Object value)
			{
				switch (index)
				{
					case 0:
						return XmlCharRef.this.setCodePoint((Integer) value);
						
					default:
						throw new IndexOutOfBoundsException();
				}
			}
		};
	}
	
	// =========================================================================
	// Children
	
	// =========================================================================
	
}
